name: simple demo

on:
  workflow_dispatch:

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      # Step showing Custom Variables with Step-level override
      - name: "Say Hello"
        run: echo "Hi Everyone its Tuesday!"
